--
-- PostgreSQL database dump
--

\restrict C4UpZ799x51x6ab51slgvYtphkhgQtXcwJ4qFw0sqofUfwv2J8BGgeBNESPAicV

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: BookTemplate; Type: TYPE; Schema: public; Owner: reactNative
--

CREATE TYPE public."BookTemplate" AS ENUM (
    'SIMPLE',
    'TRAVEL_DIARY',
    'PHOTO_ALBUM',
    'MAGAZINE',
    'MINIMALIST',
    'CLASSIC'
);


ALTER TYPE public."BookTemplate" OWNER TO "reactNative";

--
-- Name: NotificationType; Type: TYPE; Schema: public; Owner: reactNative
--

CREATE TYPE public."NotificationType" AS ENUM (
    'NEW_FOLLOWER',
    'NEW_COMMENT',
    'NEW_TIP_VOTE',
    'ROADBOOK_SHARED',
    'PLACE_RATED',
    'MENTION',
    'SYSTEM'
);


ALTER TYPE public."NotificationType" OWNER TO "reactNative";

--
-- Name: TipCategory; Type: TYPE; Schema: public; Owner: reactNative
--

CREATE TYPE public."TipCategory" AS ENUM (
    'GENERAL',
    'TRANSPORTATION',
    'FOOD',
    'ACCOMMODATION',
    'SAFETY',
    'BUDGET',
    'TIMING',
    'HIDDEN_SPOT',
    'LOCAL_CULTURE',
    'WARNING',
    'INSIDER'
);


ALTER TYPE public."TipCategory" OWNER TO "reactNative";

--
-- Name: VoteType; Type: TYPE; Schema: public; Owner: reactNative
--

CREATE TYPE public."VoteType" AS ENUM (
    'UP',
    'DOWN'
);


ALTER TYPE public."VoteType" OWNER TO "reactNative";

--
-- Name: placetype; Type: TYPE; Schema: public; Owner: reactNative
--

CREATE TYPE public.placetype AS ENUM (
    'RESTAURANT',
    'HOTEL',
    'ATTRACTION',
    'MUSEUM',
    'PARK',
    'BEACH',
    'MOUNTAIN',
    'CITY',
    'VIEWPOINT',
    'HIDDEN_GEM',
    'CAFE',
    'BAR',
    'SHOP',
    'TRANSPORTATION',
    'OTHER'
);


ALTER TYPE public.placetype OWNER TO "reactNative";

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comment; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.comment (
    id integer NOT NULL,
    user_id integer NOT NULL,
    tip_id integer NOT NULL,
    content character varying(255) NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.comment OWNER TO "reactNative";

--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO "reactNative";

--
-- Name: favorite_place; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.favorite_place (
    id integer NOT NULL,
    user_id integer NOT NULL,
    place_id integer NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.favorite_place OWNER TO "reactNative";

--
-- Name: favorite_place_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.favorite_place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_roadbook; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.favorite_roadbook (
    id integer NOT NULL,
    user_id integer NOT NULL,
    roadbook_id integer NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.favorite_roadbook OWNER TO "reactNative";

--
-- Name: favorite_roadbook_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.favorite_roadbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_roadbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.follow (
    id integer NOT NULL,
    follower_id integer NOT NULL,
    following_id integer NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.follow OWNER TO "reactNative";

--
-- Name: follow_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.follow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.place (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    address character varying(255) DEFAULT NULL::character varying,
    city character varying(255) DEFAULT NULL::character varying,
    region character varying(255) DEFAULT NULL::character varying,
    country character varying(255) NOT NULL,
    place_type public.placetype NOT NULL,
    tags character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    average_rating double precision,
    total_ratings integer DEFAULT 0 NOT NULL,
    total_tips integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.place OWNER TO "reactNative";

--
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_rating; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.place_rating (
    id integer NOT NULL,
    user_id integer NOT NULL,
    place_id integer NOT NULL,
    overall_rating integer NOT NULL,
    atmosphere_rating integer,
    value_rating integer,
    service_rating integer,
    review character varying(255) DEFAULT NULL::character varying,
    photos json,
    visit_date date,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.place_rating OWNER TO "reactNative";

--
-- Name: place_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.place_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roadbook; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.roadbook (
    id integer NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    cover_image character varying(255) DEFAULT NULL::character varying,
    start_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    end_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    countries json,
    tags json,
    is_published boolean DEFAULT false NOT NULL,
    is_public boolean DEFAULT false NOT NULL,
    template public."BookTemplate" DEFAULT 'SIMPLE'::public."BookTemplate" NOT NULL,
    theme character varying(255) DEFAULT 'default'::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    published_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    view_count integer DEFAULT 0 NOT NULL,
    favorite_count integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.roadbook OWNER TO "reactNative";

--
-- Name: roadbook_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.roadbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roadbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roadbook_stop; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.roadbook_stop (
    id integer NOT NULL,
    roadbook_id integer NOT NULL,
    place_id integer,
    title character varying(255) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    custom_location character varying(255) DEFAULT NULL::character varying,
    arrival_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    departure_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    day_number integer NOT NULL,
    order_index integer NOT NULL,
    content character varying(255) NOT NULL,
    photos json,
    mood character varying(255) DEFAULT NULL::character varying,
    weather character varying(255) DEFAULT NULL::character varying,
    temperature double precision,
    expenses double precision,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.roadbook_stop OWNER TO "reactNative";

--
-- Name: roadbook_stop_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.roadbook_stop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roadbook_stop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shared_roadbook; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.shared_roadbook (
    id integer NOT NULL,
    roadbook_id integer NOT NULL,
    shared_with_user_id integer NOT NULL,
    shared_by_user_id integer NOT NULL,
    can_edit boolean DEFAULT false NOT NULL,
    message character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.shared_roadbook OWNER TO "reactNative";

--
-- Name: shared_roadbook_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.shared_roadbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shared_roadbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tip; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.tip (
    id integer NOT NULL,
    user_id integer NOT NULL,
    place_id integer NOT NULL,
    title character varying(255) NOT NULL,
    content character varying(255) NOT NULL,
    category public."TipCategory" NOT NULL,
    photos json,
    is_warning boolean DEFAULT false NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    upvotes integer DEFAULT 0 NOT NULL,
    downvotes integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.tip OWNER TO "reactNative";

--
-- Name: tip_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.tip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tip_vote; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public.tip_vote (
    id integer NOT NULL,
    user_id integer NOT NULL,
    tip_id integer NOT NULL,
    vote_type public."VoteType" NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.tip_vote OWNER TO "reactNative";

--
-- Name: tip_vote_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public.tip_vote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tip_vote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: reactNative
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    roles json NOT NULL,
    username character varying(255) NOT NULL,
    display_name character varying(255) DEFAULT NULL::character varying,
    avatar character varying(255) DEFAULT NULL::character varying,
    bio character varying(255) DEFAULT NULL::character varying,
    password_hash character varying(255) NOT NULL,
    created_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    last_login_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    is_profile_public boolean DEFAULT true NOT NULL
);


ALTER TABLE public."user" OWNER TO "reactNative";

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: reactNative
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.comment (id, user_id, tip_id, content, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20251201085529	2025-12-01 09:08:04	39
\.


--
-- Data for Name: favorite_place; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.favorite_place (id, user_id, place_id, created_at) FROM stdin;
\.


--
-- Data for Name: favorite_roadbook; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.favorite_roadbook (id, user_id, roadbook_id, created_at) FROM stdin;
\.


--
-- Data for Name: follow; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.follow (id, follower_id, following_id, created_at) FROM stdin;
\.


--
-- Data for Name: place; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.place (id, name, description, latitude, longitude, address, city, region, country, place_type, tags, created_at, updated_at, average_rating, total_ratings, total_tips) FROM stdin;
\.


--
-- Data for Name: place_rating; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.place_rating (id, user_id, place_id, overall_rating, atmosphere_rating, value_rating, service_rating, review, photos, visit_date, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: roadbook; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.roadbook (id, user_id, title, description, cover_image, start_date, end_date, countries, tags, is_published, is_public, template, theme, created_at, updated_at, published_at, view_count, favorite_count) FROM stdin;
\.


--
-- Data for Name: roadbook_stop; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.roadbook_stop (id, roadbook_id, place_id, title, description, custom_location, arrival_date, departure_date, day_number, order_index, content, photos, mood, weather, temperature, expenses, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: shared_roadbook; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.shared_roadbook (id, roadbook_id, shared_with_user_id, shared_by_user_id, can_edit, message, created_at) FROM stdin;
\.


--
-- Data for Name: tip; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.tip (id, user_id, place_id, title, content, category, photos, is_warning, is_pinned, created_at, updated_at, upvotes, downvotes) FROM stdin;
\.


--
-- Data for Name: tip_vote; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public.tip_vote (id, user_id, tip_id, vote_type, created_at) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: reactNative
--

COPY public."user" (id, email, roles, username, display_name, avatar, bio, password_hash, created_at, updated_at, last_login_at, is_profile_public) FROM stdin;
\.


--
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.comment_id_seq', 1, false);


--
-- Name: favorite_place_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.favorite_place_id_seq', 1, false);


--
-- Name: favorite_roadbook_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.favorite_roadbook_id_seq', 1, false);


--
-- Name: follow_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.follow_id_seq', 1, false);


--
-- Name: place_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.place_id_seq', 1, false);


--
-- Name: place_rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.place_rating_id_seq', 1, false);


--
-- Name: roadbook_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.roadbook_id_seq', 1, false);


--
-- Name: roadbook_stop_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.roadbook_stop_id_seq', 1, false);


--
-- Name: shared_roadbook_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.shared_roadbook_id_seq', 1, false);


--
-- Name: tip_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.tip_id_seq', 1, false);


--
-- Name: tip_vote_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.tip_vote_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: reactNative
--

SELECT pg_catalog.setval('public.user_id_seq', 1, false);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: favorite_place favorite_place_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.favorite_place
    ADD CONSTRAINT favorite_place_pkey PRIMARY KEY (id);


--
-- Name: favorite_roadbook favorite_roadbook_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.favorite_roadbook
    ADD CONSTRAINT favorite_roadbook_pkey PRIMARY KEY (id);


--
-- Name: follow follow_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT follow_pkey PRIMARY KEY (id);


--
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- Name: place_rating place_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.place_rating
    ADD CONSTRAINT place_rating_pkey PRIMARY KEY (id);


--
-- Name: roadbook roadbook_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.roadbook
    ADD CONSTRAINT roadbook_pkey PRIMARY KEY (id);


--
-- Name: roadbook_stop roadbook_stop_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.roadbook_stop
    ADD CONSTRAINT roadbook_stop_pkey PRIMARY KEY (id);


--
-- Name: shared_roadbook shared_roadbook_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.shared_roadbook
    ADD CONSTRAINT shared_roadbook_pkey PRIMARY KEY (id);


--
-- Name: tip tip_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.tip
    ADD CONSTRAINT tip_pkey PRIMARY KEY (id);


--
-- Name: tip_vote tip_vote_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public.tip_vote
    ADD CONSTRAINT tip_vote_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: reactNative
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: reactNative
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- PostgreSQL database dump complete
--

\unrestrict C4UpZ799x51x6ab51slgvYtphkhgQtXcwJ4qFw0sqofUfwv2J8BGgeBNESPAicV

