<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251201085529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, tip_id INT NOT NULL, content VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE favorite_place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, place_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE favorite_roadbook (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, roadbook_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE follow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, follower_id INT NOT NULL, following_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, country VARCHAR(255) NOT NULL, place_type placetype NOT NULL, tags VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, average_rating DOUBLE PRECISION DEFAULT NULL, total_ratings INT DEFAULT 0 NOT NULL, total_tips INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE place_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, place_id INT NOT NULL, overall_rating INT NOT NULL, atmosphere_rating INT DEFAULT NULL, value_rating INT DEFAULT NULL, service_rating INT DEFAULT NULL, review VARCHAR(255) DEFAULT NULL, photos JSON DEFAULT NULL, visit_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE roadbook (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, countries JSON DEFAULT NULL, tags JSON DEFAULT NULL, is_published BOOLEAN DEFAULT false NOT NULL, is_public BOOLEAN DEFAULT false NOT NULL, template "BookTemplate" DEFAULT \'SIMPLE\' NOT NULL, theme VARCHAR(255) DEFAULT \'default\', created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, view_count INT DEFAULT 0 NOT NULL, favorite_count INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE roadbook_stop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roadbook_id INT NOT NULL, place_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, custom_location VARCHAR(255) DEFAULT NULL, arrival_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, departure_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, day_number INT NOT NULL, order_index INT NOT NULL, content VARCHAR(255) NOT NULL, photos JSON DEFAULT NULL, mood VARCHAR(255) DEFAULT NULL, weather VARCHAR(255) DEFAULT NULL, temperature DOUBLE PRECISION DEFAULT NULL, expenses DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE shared_roadbook (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roadbook_id INT NOT NULL, shared_with_user_id INT NOT NULL, shared_by_user_id INT NOT NULL, can_edit BOOLEAN DEFAULT false NOT NULL, message VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, place_id INT NOT NULL, title VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, category "TipCategory" NOT NULL, photos JSON DEFAULT NULL, is_warning BOOLEAN DEFAULT false NOT NULL, is_pinned BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, upvotes INT DEFAULT 0 NOT NULL, downvotes INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tip_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, tip_id INT NOT NULL, vote_type "VoteType" NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(320) NOT NULL, roles JSON NOT NULL, username VARCHAR(255) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, bio VARCHAR(255) DEFAULT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_profile_public BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE favorite_place');
        $this->addSql('DROP TABLE favorite_roadbook');
        $this->addSql('DROP TABLE follow');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE place_rating');
        $this->addSql('DROP TABLE roadbook');
        $this->addSql('DROP TABLE roadbook_stop');
        $this->addSql('DROP TABLE shared_roadbook');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE tip_vote');
        $this->addSql('DROP TABLE "user"');
    }
}
